// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzxbn3T6TBMhikLOcc4b1S2OpIMf-p9jE',
    appId: '1:315865547000:android:6ccc0d97e8948ab4187b0d',
    messagingSenderId: '315865547000',
    projectId: 'meu-amigo-secreto-5747d',
    storageBucket: 'meu-amigo-secreto-5747d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJ11YLiTGhUrAzuvIYRixRQy7a_UYjqs',
    appId: '1:315865547000:ios:300275d233e7fac6187b0d',
    messagingSenderId: '315865547000',
    projectId: 'meu-amigo-secreto-5747d',
    storageBucket: 'meu-amigo-secreto-5747d.appspot.com',
    iosClientId: '315865547000-r7p7pve9vaaa8prvfopaa9lujtuufqip.apps.googleusercontent.com',
    iosBundleId: 'br.com.viniciosdb.meuAmigoSecreto',
  );
}
