// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-fLBVCgrlz0B-SlIAeR-Mpoi54MktcE',
    appId: '1:198456589523:web:a92d6d5adcc89362e06826',
    messagingSenderId: '198456589523',
    projectId: 'meu-amigo-secreto-c8701',
    authDomain: 'meu-amigo-secreto-c8701.firebaseapp.com',
    storageBucket: 'meu-amigo-secreto-c8701.appspot.com',
    measurementId: 'G-TENCED72ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALgjqqXNEcs8jiJv9U6aZaowHB5JIy86I',
    appId: '1:198456589523:android:a6a3beac77d2e362e06826',
    messagingSenderId: '198456589523',
    projectId: 'meu-amigo-secreto-c8701',
    storageBucket: 'meu-amigo-secreto-c8701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAengwPmKWWgDf_XkhkdvnKXU5In6rCyZE',
    appId: '1:198456589523:ios:279d087a5957856ee06826',
    messagingSenderId: '198456589523',
    projectId: 'meu-amigo-secreto-c8701',
    storageBucket: 'meu-amigo-secreto-c8701.appspot.com',
    iosClientId: '198456589523-ba5773nee3fc87ka164nuotp2entdlal.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuAmigoSecreto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAengwPmKWWgDf_XkhkdvnKXU5In6rCyZE',
    appId: '1:198456589523:ios:279d087a5957856ee06826',
    messagingSenderId: '198456589523',
    projectId: 'meu-amigo-secreto-c8701',
    storageBucket: 'meu-amigo-secreto-c8701.appspot.com',
    iosClientId: '198456589523-ba5773nee3fc87ka164nuotp2entdlal.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuAmigoSecreto',
  );
}
